name: Package Deployment
on:
  workflow_dispatch:
    inputs:
      artifact:
        type: choice
        description: 'Artifact type (rpm/deb)'
        options:
          - rpm
          - deb
        required: true
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        package-manager: [deb, rpm]
        region: [us-west-2, us-east-1]
        include:
          - os: ubuntu-20.04
            package-manager: deb
          - os: ubuntu-22.04
            package-manager: rpm
    steps:
      - name: print matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.package-manager }}
          echo ${{ matrix.region }}
      
