name: Package Deployment
on:
  workflow_dispatch:
    inputs:
      package-nanager:
        type: choice
        description: 'Artifact type (rpm/deb)'
        options:
          - rpm
          - deb
        required: true
jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        region: [us-west-2, us-east-1, eu-east-2]
        include:
          - os: ubuntu-20.04
            package-manager: deb
          - os: ubuntu-22.04
            package-manager: rpm
        exclude:
          - os: ubuntu-20.04
            package-manager: rpm
          - os: ubuntu-22.04
            package-manager: deb
          - region: eu-east-2
            environment: nonprod
    steps:
      - name: print matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.package-manager }}
          echo ${{ matrix.region }}
      
