name: Package Deployment

on:
  workflow_dispatch:
    inputs:
      package-manager:
        type: choice
        description: 'Artifact type (rpm/deb)'
        options:
          - rpm
          - deb
        required: true
      environment:
        type: choice
        description: 'Environment'
        options:
          - prod
          - nonprod
        required: true

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"include\": ["
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            cat <<EOF
            {"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"us-west-2"},
            {"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"us-east-1"},
            {"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"eu-east-2"},
            {"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"us-west-2"},
            {"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"us-east-1"},
            {"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"eu-east-2"}
            EOF
          else
            cat <<EOF
            {"os":"ubuntu-20.04","package-manager":"deb","environment":"nonprod","region":"us-west-2"},
            {"os":"ubuntu-20.04","package-manager":"deb","environment":"nonprod","region":"us-east-1"},
            {"os":"ubuntu-22.04","package-manager":"rpm","environment":"nonprod","region":"us-west-2"},
            {"os":"ubuntu-22.04","package-manager":"rpm","environment":"nonprod","region":"us-east-1"}
            EOF
          fi
          echo "]}"

  deploy:
    needs: setup-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.setup-matrix.outputs.matrix)}}
    steps:
      - name: print matrix
        run: |
          echo "${{ matrix.os }}"
          echo "${{ matrix.package-manager }}"
          echo "${{ matrix.region }}"
