name: Package Deployment

on:
  workflow_dispatch:
    inputs:
      package-manager:
        type: choice
        description: 'Artifact type (rpm/deb)'
        options:
          - rpm
          - deb
        required: true
      environment:
        type: choice
        description: 'Environment'
        options:
          - prod
          - nonprod
        required: true

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            matrix_value='[{"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"us-west-2"},{"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"us-east-1"},{"os":"ubuntu-20.04","package-manager":"deb","environment":"prod","region":"eu-east-2"},{"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"us-west-2"},{"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"us-east-1"},{"os":"ubuntu-22.04","package-manager":"rpm","environment":"prod","region":"eu-east-2"}]'
          else
            matrix_value='[{"os":"ubuntu-20.04","package-manager":"deb","environment":"nonprod","region":"us-west-2"},{"os":"ubuntu-20.04","package-manager":"deb","environment":"nonprod","region":"us-east-1"},{"os":"ubuntu-22.04","package-manager":"rpm","environment":"nonprod","region":"us-west-2"},{"os":"ubuntu-22.04","package-manager":"rpm","environment":"nonprod","region":"us-east-1"}]'
          fi
          echo "matrix=$matrix_value" >> $GITHUB_ENV
          echo "::set-output name=matrix::$matrix_value"

  deploy:
    needs: setup-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: print matrix
        run: |
          echo "Operating System: ${{ matrix.os }}"
          echo "Package Manager: ${{ matrix.package-manager }}"
          echo "Region: ${{ matrix.region }}"
